server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store";
  }

  location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|json|wasm)$ {
    try_files $uri =404;
    expires -1;
    add_header Cache-Control "no-store";
  }
}
